name = "FreeParameters"
uuid = "c2bd907f-6643-4f95-bba2-6fb2889bb36c"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.2.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
SyntaxTree = "a4af3ec5-f8ac-5fed-a759-c2e80b4d74cb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Distributions = "0.22.4"
SyntaxTree = "1.0.1"
julia = "1.0"
